"""add_tsv_column

Revision ID: c8b9717e2b7f
Revises: 7a3ef5dd03b1
Create Date: 2026-06-27 18:09:55.181017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8b9717e2b7f'
down_revision: Union[str, Sequence[str], None] = '7a3ef5dd03b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(body, '')), 'B')", persisted=True), nullable=False))
    # ### end Alembic commands ###
    op.execute("CREATE INDEX ix_notes_tsv ON notes USING gin(tsv)")



def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_notes_tsv")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'tsv')
    # ### end Alembic commands ###